export type VarKey =
  | "PUBLIC_BASE_URL"
  | "PAYMENT_PROVIDER"
  | "PAYMENT_NOTIFY_URL"
  | "WECHAT_PAY_APP_ID"
  | "WECHAT_PAY_MCH_ID"
  | "SMS_PROVIDER"
  | "VOICE_PROVIDER"
  | "TASK_QUEUE_NAME"
  | "ADMIN_INITIAL_USERNAME";

export type SecretKey =
  | "ADMIN_INITIAL_PASSWORD"
  | "ADMIN_PASSWORD_PEPPER"
  | "WECHAT_PAY_API_V3_KEY"
  | "WECHAT_PAY_PRIVATE_KEY"
  | "WECHAT_PAY_CERT_SERIAL_NO"
  | "SMS_API_KEY"
  | "SMS_API_SECRET"
  | "VOICE_API_KEY"
  | "VOICE_API_SECRET";
